config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  devise_for :users
  resource :posts
  resource :profiles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  has_attached_file :image, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  
end

app/models/profile.rb
class Profile < ApplicationRecord
  has_attached_file :avatar, styles: { medium: "200x200>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :profile
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	
  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
     @post = current_user.posts.build(post_params)
     if @post.save
      flash[:success] = "Your post has been created!"
      redirect_to root_path
    else
      flash.now[:alert] = "Your new post couldn't be created!  Please check the form."
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:success] = "Post updated."
      redirect_to root_path
    else
      flash.now[:alert] = "Update failed.  Please check the form."
      render :edit
    end
  end

  def destroy
    if @post.destroy
    redirect_to root_path
   end
  end


  private

	def post_params
	  params.require(:post).permit(:image, :title)
    end

    def set_post
      @post = Post.find(params[:id])
    end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def new
    @profile = Profile.new
  end
  
  def create
    @profile = current_user.build_profile(profile_params)
    if @profile.save
      redirect_to profiles_path(@profile.id)
    end
    
  end
  
  def show
    @profile = current_user.profile
  end
  
  def edit
    @profile = current_user.profile
  end
  
  def update
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile.update(profile_params)
       redirect_to profiles_path(@profile.id)
    end
    
  end
  
private

  def profile_params
    params.require(:profile).permit(:user_id, :nickname, :age, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <!-- Brand/logo -->
   <%= link_to root_path, class: "nav-logo" do  %>
        
      <% end %>
  <ul class="navbar-nav">
    <li class= "nav-link1">Insta<li>
  </ul>
  <!-- Links -->
  <ul class="navbar-nav ml-auto">
    <% if !user_signed_in? %>
      <%= link_to user_session_path, class: "nav-link" do  %>
        <i class="fas fa-sign-in-alt"> Login</i> 
      <% end %>

      <%= link_to new_user_registration_path, class: "nav-link" do  %>
        <i class="fab fa-instagram"> Registration</i> 
      <% end %>
  
    <%else%>
      <%= link_to new_posts_path, class: "nav-link" do  %>
        <i class="far fa-newspaper"> New post</i> 
      <% end %>
       <%if current_user.profile.nil?%> 
           <%= link_to new_profiles_path, class: "nav-link" do  %>
          <i class="fas fa-user-circle"> Me</i> 
          <%end%>
      <% else %>
           <%= link_to profiles_path(current_user.id), class: "nav-link" do  %>
          <i class="fas fa-user-circle"> Me</i>  
      <%end%>
      <% end %>
      
       <%= link_to destroy_user_session_path, method: :delete, class: "nav-link" do  %>
        <i class="fas fa-sign-out-alt"> Log out</i> 
      <% end %>
    <%end%>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/header"%>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-4"></div>
		<div class="col-4">
	<% if @posts == [] %>
    	<p>Create new post</p>
	<% else %>
    <% @posts.each do |post| %>
    <p><%= image_tag post.image.url(:medium)%><br></p>
    <p><%=link_to post.user.profile.nickname, profiles_path%></p>
    <p><i> <%= post.title%></i><br/></p>
    <%if%>
      <%current_user.id == post.user.id%>
      <%= link_to "Delete post", posts_path(post.user.id), method: :delete%>
    <%end%>
   		<%end%>
	<%end%>
      </div>
     	 <div class="col-4"></div>
     </div>
</div>
  

app/views/posts/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-4"></div>
    <div class="col-4">
      <%= form_for @post, url: posts_path do |f| %>

    <% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
     <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "form"  %>
  </div>
   
       <div class="field1">
    <%= f.file_field :image %>
    </div>
   <div class="actions">
        <%= f.submit "Upload", class: "btn btn-primary" %>
      </div>
<% end %>
</div>
<div class="col-4"></div>
</div>
</div>

app/views/profiles/edit.html.erb
<%= form_for @profile, url: profiles_path do |f| %>

<% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  Nickname: <%= f.text_field :nickname %><br />
  Age: <%= f.text_field :age %><br />
  Description: <%= f.text_field :description %><br />
  <%= f.file_field :avatar %><br />

  <%= f.submit "Update" %>
<% end %>

app/views/profiles/new.html.erb
<%= form_for @profile, url: profiles_path do |f| %>

<% if @profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this post from being saved:</h2>
 
    <ul>
    <% @profile.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

  Nickname: <%= f.text_field :nickname %><br />
  Age: <%= f.text_field :age %><br />
  Description: <%= f.text_field :description %><br />
  <%= f.file_field :image %><br />

  <%= f.submit "Create" %>
<% end %>

app/views/profiles/show.html.erb
<%= image_tag current_user.profile.avatar.url %><br>
Firstname: <%= current_user.profile.nickname %><br />
Age: <%= current_user.profile.age %><br />
Description: <%= current_user.profile.description %><br />
<%= link_to "Update", edit_profiles_path(current_user.id)%>